### ISSUE TITLE
login section

### ISSUE THREAD

**Issue by Dhruv031003** [Dhruv031003/transparent-login#2]
login section going out of page
![image](https://user-images.githubusercontent.com/91516121/194842053-10a85dcd-3a39-42eb-96b6-afe18f52d232.png)

- [ ] fix login section
- [ ] color change of login section

**Comment by Ayushsahrawat** [comment]
hi

**Comment by Ayushsahrawat** [comment]
i would like to work on this project

**Comment by Dhruv031003** [comment]
okay i am assigning this to you
